version: "3.9"

# Описываем сервисы приложения
services:
  # Сервис django-приложения
  web:
    # Создаём образ
    build: .
    # Собираем статические файлы и запускаем gunicorn сервер
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - habits_static_volume:/app/staticfiles
      - habits_media_volume:/app/media
    # Открываем порт 8000 внутри docker-сети
    ports:
      - "8000:8000"
    # Указываем, что сервис зависит от БД и редис
    depends_on:
      - db
      - redis
    # Подключаем файл с переменными окружения
    env_file:
      - ./.env

  # Сервис БД postgresql
  db:
    # Используем официальный образ postgresql версии 16
    image: postgres:16
    container_name: habits_db
    # Монтируем том для хранения данных БД
    volumes:
      - habits_postgres_data:/var/lib/postgresql/data/
    # Подключаем файл с переменными окружения
    env_file:
       - ./.env

  # Сервис редис
  redis:
    # Используем официальный образ редис
    image: redis:7
    container_name: habits_redis
    # Монтируем том для хранения данных редис
    volumes:
      - habits_redis_data:/data
    # Подключаем файл с переменными окружения
    env_file:
      - ./.env

  # Сервис celery
  celery:
    build: .
    container_name: habits_celery
    command: celery -A config worker -l info
    # Монтируем том для хранения данных celery
    depends_on:
      - db
      - redis
    # Подключаем файл с переменными окружения
    env_file:
      - ./.env

  # Сервис celery beat
  celery-beat:
    build: .
    container_name: habits_celery-beat
    command: celery -A config beat -l info
    # Монтируем том для хранения данных celery beat
    depends_on:
      - db
      - redis
    # Подключаем файл с переменными окружения
    env_file:
      - ./.env

# Объявляем тома для сохранения данных между перезапусками
volumes:
  habits_postgres_data:
  habits_static_volume:
  habits_redis_data:
  habits_media_volume:
