# Generated by Django 6.0 on 2026-01-06 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Place")),
                ("time", models.TimeField(verbose_name="Time")),
                ("action", models.CharField(max_length=255, verbose_name="Action")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Is pleasant")),
                (
                    "reward",
                    models.CharField(
                        blank=True, help_text="Enter reward", max_length=255, null=True, verbose_name="Reward"
                    ),
                ),
                ("periodicity", models.PositiveSmallIntegerField(default=1, verbose_name="Periodicity (days)")),
                ("duration", models.PositiveSmallIntegerField(verbose_name="Duration (seconds)")),
                ("is_public", models.BooleanField(default=False, verbose_name="Is public")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="habits.habit",
                        verbose_name="Related habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
    ]
