# Generated by Django 6.0 on 2026-01-06 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(120)], verbose_name="Duration (seconds)"
            ),
        ),
    ]
